# -*- coding: utf-8 -*-
"""LiveStarPro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FP5dnPXRhie0sxeBT_W-hFhLKh9SHll9
"""

!pip install openai
!pip install opencv-python pillow tqdm

OPENROUTER_API_KEY = "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"

import cv2
import base64
import json
from PIL import Image
from tqdm import tqdm

from openai import OpenAI

client = OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1"
)

from google.colab import files

uploaded = files.upload()

VIDEO_PATH = list(uploaded.keys())[0]

print(VIDEO_PATH)

cap = cv2.VideoCapture(VIDEO_PATH)

fps = cap.get(cv2.CAP_PROP_FPS)

interval = int(fps * 5)

frames = []

count = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    if count % interval == 0:
        frames.append(frame)

    count += 1

cap.release()

print("Frames:", len(frames))

def frame_to_base64(frame):

    _, buffer = cv2.imencode(".jpg", frame)

    return base64.b64encode(buffer).decode()

VISION_MODEL = "google/gemini-2.5-flash"

def describe_frame(frame):

    image_b64 = frame_to_base64(frame)

    response = client.chat.completions.create(
        model=VISION_MODEL,
        max_tokens=100,
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "Describe the main event in this image in one short sentence."
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{image_b64}"
                        }
                    }
                ]
            }
        ]
    )

    return response.choices[0].message.content

events = []

for idx, frame in enumerate(tqdm(frames)):

    description = describe_frame(frame)

    event = {
        "frame": idx,
        "event": description
    }

    events.append(event)

    print(description)

import json

with open("events.json", "w") as f:
    json.dump(events, f, indent=2)

print(f"Saved {len(events)} events")

TEXT_MODEL = "google/gemini-2.5-flash"

def summarize_events(event_block):

    text = "\n".join(
        e["event"] for e in event_block
    )

    prompt = f"""
Summarize these video events in one concise sentence.

Events:
{text}
"""

    response = client.chat.completions.create(
        model=TEXT_MODEL,
        max_tokens=50,
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content.strip()

memory = []

BLOCK_SIZE = 5

for i in range(0, len(events), BLOCK_SIZE):

    block = events[i:i+BLOCK_SIZE]

    summary = summarize_events(block)

    memory.append(summary)

    print(f"\nMemory Node {len(memory)}")
    print(summary)

all_memory = "\n".join(memory)

prompt = f"""
Summarize this entire video.

Memory:
{all_memory}

Use 2-3 sentences.
"""

response = client.chat.completions.create(
    model=TEXT_MODEL,
    max_tokens=100,
    temperature=0,
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ]
)

session_summary = response.choices[0].message.content.strip()

print("\nVIDEO SUMMARY\n")
print(session_summary)

def should_speak(event):

    prompt = f"""
Event:

{event}

Would a live assistant proactively comment on this?

Reply only YES or NO.
"""

    response = client.chat.completions.create(
        model=TEXT_MODEL,
        max_tokens=3,
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content.strip()

def generate_comment(event):

    prompt = f"""
Create a short live commentary.

Event:
{event}

Maximum 15 words.
"""

    response = client.chat.completions.create(
        model=TEXT_MODEL,
        max_tokens=30,
        temperature=0.5,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )

    return response.choices[0].message.content.strip()

for event in events:

    decision = should_speak(
        event["event"]
    )

    if "YES" in decision.upper():

        comment = generate_comment(
            event["event"]
        )

        print("\n----------------")
        print("EVENT:")
        print(event["event"])

        print("\nASSISTANT:")
        print(comment)

print("\n========== MEMORY TREE ==========\n")

for idx, node in enumerate(memory):

    print(f"Node {idx+1}")
    print(node)
    print()

results = {
    "events": events,
    "memory": memory,
    "video_summary": session_summary
}

with open("livestar_results.json", "w") as f:
    json.dump(results, f, indent=2)

print("Saved to livestar_results.json")

from google.colab import files

files.download("livestar_results.json")

